### ISSUE TITLE
BUSCO error = BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by cahuparo** [nf-core/pathogensurveillance#118]
New errror with busco

```
ERROR ~ Error executing process > 'PATHOGENSURVEILLANCE:BUSCO_PHYLOGENY:BUSCO (ND822Pi_US_24)'

Caused by:
  Process `PATHOGENSURVEILLANCE:BUSCO_PHYLOGENY:BUSCO (ND822Pi_US_24)` terminated with an error exit status (137)


Command executed:

  # Nextflow changes the container --entrypoint to /bin/bash (container default entrypoint: /usr/local/env-execute)
  # Check for container variable initialisation script and source it.
  if [ -f "/usr/local/env-activate.sh" ]; then
      set +u  # Otherwise, errors out because of various unbound variables
      . "/usr/local/env-activate.sh"
      set -u
  fi
 
  # If the augustus config directory is not writable, then copy to writeable area
  if [ ! -w "${AUGUSTUS_CONFIG_PATH}" ]; then
      # Create writable tmp directory for augustus
      AUG_CONF_DIR=$( mktemp -d -p $PWD )
      cp -r $AUGUSTUS_CONFIG_PATH/* $AUG_CONF_DIR
      export AUGUSTUS_CONFIG_PATH=$AUG_CONF_DIR
      echo "New AUGUSTUS_CONFIG_PATH=${AUGUSTUS_CONFIG_PATH}"
  fi
 
  # Ensure the input is uncompressed
  INPUT_SEQS=input_seqs
  mkdir "$INPUT_SEQS"
  cd "$INPUT_SEQS"
  for FASTA in ../tmp_input/*; do
      if [ "${FASTA##*.}" == 'gz' ]; then
          gzip -cdf "$FASTA" > $( basename "$FASTA" .gz )
      else
          ln -s "$FASTA" .
      fi
  done
  cd ..
 
  busco \
      --cpu 12 \
      --in "$INPUT_SEQS" \
      --out ND822Pi_US_24-eukaryota_odb10-busco \
      --mode genome \
      --lineage_dataset eukaryota_odb10 \
      --offline --download_path busco_downloads \
       \
 
 
  # clean up
  rm -rf "$INPUT_SEQS"
 
  # Move files to avoid staging/publishing issues
  mv ND822Pi_US_24-eukaryota_odb10-busco/batch_summary.txt ND822Pi_US_24-eukaryota_odb10-busco.batch_summary.txt
  mv ND822Pi_US_24-eukaryota_odb10-busco/*/short_summary.*.{json,txt} . || echo "Short summaries were not available: No genes were found."
 
  cat <<-END_VERSIONS > versions.yml
  "PATHOGENSURVEILLANCE:BUSCO_PHYLOGENY:BUSCO":
      busco: $( busco --version 2>&1 | sed 's/^BUSCO //' )
  END_VERSIONS

Command exit status:
  137

Command output:
  2024-11-19 04:32:18 INFO:     ***** Start a BUSCO v5.7.1 analysis, current time: 11/19/2024 04:32:18 *****
  2024-11-19 04:32:18 INFO:     Configuring BUSCO with local environment
  2024-11-19 04:32:18 INFO:     Running genome mode
  2024-11-19 04:32:18 INFO:     Running in batch mode. 1 input files found in input_seqs
  2024-11-19 04:32:18 INFO:
 
  ********************************************************************************
  Running BUSCO on file: input_seqs/ND822Pi_US_24_filtered.fasta
  ********************************************************************************
 
 
  2024-11-19 04:32:18 INFO:     Input file is input_seqs/ND822Pi_US_24_filtered.fasta
  2024-11-19 04:32:22 INFO:     Running BUSCO using lineage dataset eukaryota_odb10 (eukaryota, 2024-01-08)
  2024-11-19 04:32:22 INFO:     Running 1 job(s) on bbtools, starting at 11/19/2024 04:32:22
  2024-11-19 04:32:25 INFO:     [bbtools]       1 of 1 task(s) completed
  2024-11-19 04:32:25 INFO:     Running 1 job(s) on miniprot_index, starting at 11/19/2024 04:32:25
  2024-11-19 04:32:31 INFO:     [miniprot_index]        1 of 1 task(s) completed
  2024-11-19 04:32:31 INFO:     Running 1 job(s) on miniprot_align, starting at 11/19/2024 04:32:31
  2024-11-19 04:38:20 INFO:     [miniprot_align]        1 of 1 task(s) completed

Command error:
  Traceback (most recent call last):
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
      self.run()
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/process.py", line 99, in run
      self._target(*self._args, **self._kwargs)
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/pool.py", line 132, in worker
      put((job, i, (False, wrapped)))
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/queues.py", line 364, in put
      self._writer.send_bytes(obj)
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
      self._send_bytes(m[offset:offset + size])
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/connection.py", line 397, in _send_bytes
      self._send(header)
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/connection.py", line 368, in _send
      n = write(self._handle, buf)
  BrokenPipeError: [Errno 32] Broken pipe
  Process SpawnPoolWorker-43:
  Traceback (most recent call last):
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/pool.py", line 127, in worker
      put((job, i, result))
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/queues.py", line 364, in put
      self._writer.send_bytes(obj)
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
      self._send_bytes(m[offset:offset + size])
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/connection.py", line 397, in _send_bytes
      self._send(header)
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/connection.py", line 368, in _send
      n = write(self._handle, buf)
  BrokenPipeError: [Errno 32] Broken pipe
 
  During handling of the above exception, another exception occurred:
 
  Traceback (most recent call last):
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
      self.run()
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/process.py", line 99, in run
      self._target(*self._args, **self._kwargs)
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/pool.py", line 132, in worker
      put((job, i, (False, wrapped)))
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/queues.py", line 364, in put
      self._writer.send_bytes(obj)
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
      self._send_bytes(m[offset:offset + size])
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/connection.py", line 397, in _send_bytes
      self._send(header)
    File "/fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/connection.py", line 368, in _send
      n = write(self._handle, buf)
  BrokenPipeError: [Errno 32] Broken pipe
  /fs1/local/cqls/software/x86_64/busco-5.7.1/envs/busco/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 4 leaked semaphores to clean up at shutdown
    len(cache))

Work dir:
  /nfs7/BPP/Grunwald_Lab/home/paradarc/crispr_dx/pinf/scripts/pathogensurveillance/work/92/fbeb87af6d121d6423e0451850c259

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
ERROR ~ Pipeline failed. Please refer to troubleshooting docs: https://nf-co.re/docs/usage/troubleshooting

 -- Check '.nextflow.log' file for details
```

**Comment by zachary-foster** [comment]
close due to age of issue. It is probably no longer a problem
