### ISSUE TITLE
DOWNLOAD_ASSEMBLIES error

### ISSUE THREAD

**Issue by cahuparo** [nf-core/pathogensurveillance#25]
**ERROR**

When running test dataset, I encountered the following error message:

```shell
Oct-01 20:44:22.606 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NFCORE_PATHOGENSURVEILLANCE:PATHOGENSURVEILLANCE:DOWNLOAD_REFERENCES:DOWNLOAD_ASSEMBLIES (); work-dir=/nfs7/BPP/Chang_Lab/paradarc/brady/scripts/pathogensurveillance/work/61/f103677a0f4221ac1d21792a1828ff
  error [nextflow.exception.ProcessFailedException]: Process `NFCORE_PATHOGENSURVEILLANCE:PATHOGENSURVEILLANCE:DOWNLOAD_REFERENCES:DOWNLOAD_ASSEMBLIES ()` terminated with an error exit status (1)
Oct-01 20:44:22.606 [Task monitor] INFO  nextflow.processor.TaskProcessor - [61/f10367] NOTE: Process `NFCORE_PATHOGENSURVEILLANCE:PATHOGENSURVEILLANCE:DOWNLOAD_REFERENCES:DOWNLOAD_ASSEMBLIES ()` terminated with an error exit status (1) -- Error is ignore
Oct-01 20:44:22.620 [Actor Thread 121] ERROR nextflow.extension.OperatorImpl - @unknown
java.lang.NullPointerException: Cannot execute null+[/nfs7/BPP/Chang_Lab/paradarc/brady/scripts/pathogensurveillance/work/7b/d1bb304e828bb1dca4e122b05b0b4a/22_331_assembly.sig]
        at org.codehaus.groovy.runtime.NullObject.plus(NullObject.java:135)
        at org.codehaus.groovy.runtime.NullObject$plus$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:74)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at Script_abdb686a$_runScript_closure1$_closure2$_closure13.doCall(Script_abdb686a:78)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at nextflow.extension.MapOp$_apply_closure1.doCall(MapOp.groovy:56)
        at jdk.internal.reflect.GeneratedMethodAccessor216.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
        at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
        at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
        at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
        at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
        at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
        at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Oct-01 20:44:22.632 [Actor Thread 121] DEBUG nextflow.Session - Session aborted -- Cause: Cannot execute null+[/nfs7/BPP/Chang_Lab/paradarc/brady/scripts/pathogensurveillance/work/7b/d1bb304e828bb1dca4e122b05b0b4a/22_331_assembly.sig]
```

**Comment by zachary-foster** [comment]
I expect this has been fixed by changes made in the last few days

**Comment by zachary-foster** [comment]
I expect this is not an issue anymore. Reopen if otherwise
