### ISSUE TITLE
Circos error within bakta

### ISSUE THREAD

**Issue by cahuparo** [nf-core/pathogensurveillance#29]
As part or testing the pipeline with a larger dataset and more realistic files. It seems like one of the samples produced an assembly with lots of contigs. Based on the issue here: https://github.com/oschwengers/bakta/issues/174 this could cause circos to clog.  I am testing if adding the `--skip-plot` flag actually helps. 

```nextflow
Oct-11 20:03:40.398 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_PATHOGENSURVEILLANCE:PATHOGENSURVEILLANCE:GENOME_ASSEMBLY:BAKTA_BAKTA (H1_10_30-2_S99)'

Caused by:
  Process `NFCORE_PATHOGENSURVEILLANCE:PATHOGENSURVEILLANCE:GENOME_ASSEMBLY:BAKTA_BAKTA (H1_10_30-2_S99)` terminated with an error exit status (1)

Command executed:

  bakta \
      H1_10_30-2_S99_filtered.fasta \
      --force \
      --threads 4 \
      --prefix H1_10_30-2_S99 \
       \
       \
      --db db-light
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_PATHOGENSURVEILLANCE:PATHOGENSURVEILLANCE:GENOME_ASSEMBLY:BAKTA_BAKTA":
      bakta: $(echo $(bakta --version) 2>&1 | cut -f '2' -d ' ')
  END_VERSIONS

Command exit status:
  1

Command output:
        discarded spurious: 15
        detected IPSs: 0
        found PSCCs: 0
        lookup annotations...
        filter and combine annotations...
        filtered sORFs: 0
  detect gaps...
        found: 115
  detect oriCs/oriVs...
        found: 1
  detect oriTs...
        found: 0
  apply feature overlap filters...
  select features and create locus tags...
  selected: 14391
  improve annotations...
        revised gene symbols: 0
  
  genome statistics:
        Genome size: 13,369,953 bp
        Contigs/replicons: 20891
        GC: 64.2 %
        N50: 1,121
        N ratio: 0.1 %
        coding density: 50.6 %
  
  annotation summary:
        tRNAs: 106
        tmRNAs: 1
        rRNAs: 3
        ncRNAs: 27
        ncRNA regions: 22
        CRISPR arrays: 0
        CDSs: 14116
                hypotheticals: 9749
                pseudogenes: 0
                signal peptides: 0
        sORFs: 0
        gaps: 115
        oriCs/oriVs: 1
        oriTs: 0
  
  export annotation results to: /nfs1/BPP/Grunwald_Lab/home/paradarc/pathogensurveillance/work/c0/b4330e92b8805ce2508a106c25313e
        human readable TSV...
        GFF3...
        INSDC GenBank & EMBL...
        genome sequences...
        feature nucleotide sequences...
        translated CDS sequences...
        circular genome plot...

Command error:
        found: 1
  detect oriTs...
        found: 0
  apply feature overlap filters...
  select features and create locus tags...
  selected: 14391
  improve annotations...
        revised gene symbols: 0
  
  genome statistics:
        Genome size: 13,369,953 bp
        Contigs/replicons: 20891
        GC: 64.2 %
        N50: 1,121
        N ratio: 0.1 %
        coding density: 50.6 %
  
  annotation summary:
        tRNAs: 106
        tmRNAs: 1
        rRNAs: 3
        ncRNAs: 27
        ncRNA regions: 22
        CRISPR arrays: 0
        CDSs: 14116
                hypotheticals: 9749
                pseudogenes: 0
                signal peptides: 0
        sORFs: 0
        gaps: 115
        oriCs/oriVs: 1
        oriTs: 0
  
  export annotation results to: /nfs1/BPP/Grunwald_Lab/home/paradarc/pathogensurveillance/work/c0/b4330e92b8805ce2508a106c25313e
        human readable TSV...
        GFF3...
        INSDC GenBank & EMBL...
        genome sequences...
        feature nucleotide sequences...
        translated CDS sequences...
        circular genome plot...
  Traceback (most recent call last):
    File "/nfs1/BPP/Grunwald_Lab/home/paradarc/pathogensurveillance/work/conda/env-a426d411c02c15e446ce4ad992ac0c99/bin/bakta", line 10, in <module>
      sys.exit(main())
               ^^^^^^
    File "/nfs1/BPP/Grunwald_Lab/home/paradarc/pathogensurveillance/work/conda/env-a426d411c02c15e446ce4ad992ac0c99/lib/python3.11/site-packages/bakta/main.py", line 562, in main
      plot.write_plot(features, contigs, cfg.output_path)
    File "/nfs1/BPP/Grunwald_Lab/home/paradarc/pathogensurveillance/work/conda/env-a426d411c02c15e446ce4ad992ac0c99/lib/python3.11/site-packages/bakta/plot.py", line 259, in write_plot
      raise Exception(f'circos error! error code: {proc.returncode}')
  Exception: circos error! error code: 255

Work dir:
  /nfs1/BPP/Grunwald_Lab/home/paradarc/pathogensurveillance/work/c0/b4330e92b8805ce2508a106c25313e

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

**Comment by zachary-foster** [comment]
I disabled the plotting for now. We should try running `bakta` with the `--debug` option to see what the `circos` error is in case it is an easy fix.

**Comment by zachary-foster** [comment]
I reran this with `--debug` and indeed the issue is that there are more than 10,000 contigs, and circos is made to throw an error when that happens. I dont see a way to change that limit using bakta commands, so I think just disabling the plot, like has already been done, should be good enough. If we need a circos plot, we can make our own when the report is made.

```
debuggroup summary 1.98s karyotype has 20891 chromosomes of total size 13,390,844

  *** CIRCOS ERROR ***

      cwd: /tmp/tmp1e0sf6lf

      command: /home/fosterz/miniconda3/envs/bakta/bin/circos -conf
      /tmp/tmp1e0sf6lf/circos/main.conf

  You have asked to draw [20891] ideograms, but the maximum is currently set at
  [10000]. To increase this number change max_ideograms in
  etc/housekeeping.conf. Keep in mind that drawing that many ideograms may
  create an image that is too busy and uninterpretable.

  If you are having trouble debugging this error, first read the best practices
  tutorial for helpful tips that address many common problems

      http://www.circos.ca/documentation/tutorials/reference/best_practices

  The debugging facility is helpful to figure out what's happening under the
  hood

      http://www.circos.ca/documentation/tutorials/configuration/debugging

  If you're still stumped, get support in the Circos Google Group.

      http://groups.google.com/group/circos-data-visualization

  Please include this error, all your configuration, data files and the version
  of Circos you're running (circos -v). Do not email me directly -- please use
  the group.

  Stack trace:
', stderr=' at /home/fosterz/miniconda3/envs/bakta/bin/../lib/Circos/Error.pm line 425, <F> line 20891.
        Circos::Error::fatal_error("ideogram", "max_number", 20891, 10000) called at /home/fosterz/miniconda3/envs/bakta/bin/>
        Circos::run("Circos", "_argv", "-conf /tmp/tmp1e0sf6lf/circos/main.conf", "configfile", "/tmp/tmp1e0sf6lf/circos/main>
'
19:21:43.377 - WARNING - PLOT - Circos failed! circos-error-code=255
```

**Comment by zachary-foster** [comment]
done
