### ISSUE TITLE
Error when testing xanthomonas small dataset

### ISSUE THREAD

**Issue by buchanri** [nf-core/pathogensurveillance#81]
### Description of the bug

I installed nextflow and the latest version of the pipeline. I wanted to test it first on one of the test datasets but I got an error. I was wondering if this is a issue with the pipeline or just the test dataset I used?

### Command used and terminal output

```console
Input:

nextflow run main.nf --sample_data https://raw.githubusercontent.com/grunwaldlab/pathogensurveillance/master/test/data/metadata/xanthomonas_small.csv --out_dir /nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/pathogensurveillance/test/data/xan_small --download_bakta_db true -profile mamba --max_memory 200.GB --max_time 240.h --email_on_fail buchanri@oregonstate.edu --max_cpus 32 -resume --temp_dir /nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/pathogensurveillance/tmp 
```

Output:
```
ERROR ~ Error executing process > 'PATHOGENSURVEILLANCE:GENOME_ASSEMBLY:BAKTA_BAKTA (22_335)'

Caused by:
  Process `PATHOGENSURVEILLANCE:GENOME_ASSEMBLY:BAKTA_BAKTA (22_335)` terminated with an error exit status (1)


Command executed:

  bakta \
      22_335_filtered.fasta \
      --force --skip-plot --skip-crispr \
      --threads 8 \
      --prefix 22_335 \
       \
       \
      --db db-light
 
  cat <<-END_VERSIONS > versions.yml
  "PATHOGENSURVEILLANCE:GENOME_ASSEMBLY:BAKTA_BAKTA":
      bakta: $(echo $(bakta --version) 2>&1 | cut -f '2' -d ' ')
  END_VERSIONS

Command exit status:
  1

Command output:
 
  parse genome sequences...
        imported: 241
        filtered & revised: 241
        contigs: 241
 
  start annotation...
  predict tRNAs...
        found: 1
  predict tmRNAs...
        found: 0
  predict rRNAs...
        found: 0
  predict ncRNAs...
        found: 1
  predict ncRNA regions...
        found: 0
  skip CRISPR array prediction...
  predict & annotate CDSs...
        predicted: 66
        discarded spurious: 0
        revised translational exceptions: 0
        detected IPSs: 0

Command error:
  /nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/pathogensurveillance/work/conda/bakta_bakta-49113c86da635f9641eee48fb966e3b9/lib/python3.10/site-packages/bakta/features/cds.py:43: UserWarning: sequence should be at least 100000 characters (88372 found)
    trainings_info = orffinder.train(*seqs, translation_table=cfg.translation_table)
 
  parse genome sequences...
        imported: 241
        filtered & revised: 241
        contigs: 241
 
  start annotation...
  predict tRNAs...
        found: 1
  predict tmRNAs...
        found: 0
  predict rRNAs...
        found: 0
  predict ncRNAs...
        found: 1
  predict ncRNA regions...
        found: 0
  skip CRISPR array prediction...
  predict & annotate CDSs...
        predicted: 66
        discarded spurious: 0
        revised translational exceptions: 0
        detected IPSs: 0
  Traceback (most recent call last):
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/pathogensurveillance/work/conda/bakta_bakta-49113c86da635f9641eee48fb966e3b9/bin/bakta", line 11, in <module>
      sys.exit(main())
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/pathogensurveillance/work/conda/bakta_bakta-49113c86da635f9641eee48fb966e3b9/lib/python3.10/site-packages/bakta/main.py", line 258, in main
      cdss_pscc, cdss_not_found = pscc.search(cdss_not_found)
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/pathogensurveillance/work/conda/bakta_bakta-49113c86da635f9641eee48fb966e3b9/lib/python3.10/site-packages/bakta/pscc.py", line 57, in search
      raise Exception(f'diamond error! error code: {proc.returncode}')
  Exception: diamond error! error code: -11

Work dir:
  /nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/pathogensurveillance/work/0f/4d91768653b6517e713a91e466cfcc

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details

-[nf-core/plantpathsurveil] Sent summary e-mail to buchanri@oregonstate.edu (sendmail)-
WARN: Access to undefined parameter `outdir` -- Initialise it to a default value eg. `params.outdir = some_value`
-[nf-core/plantpathsurveil] Pipeline completed with errors

 To clean the cache, run the command:
 nextflow clean cranky_coulomb -f

WARN: Killing running tasks (2)
```
```


### Relevant files

_No response_

### System information

Container: Conda

**Comment by zachary-foster** [comment]
I assume this has been fixed. Let me know if you still have this error and I can reopen
